spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: config-dev
server:
  port: 3355
---
spring:
  profiles: test
  application:
    name: config-test
server:
  port: 3366